-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/17/2024 12:54:14 AM
-- Server version: 5.5.5-10.4.28-MariaDB
-- Client version: 4.1

USE edm;

CREATE TABLE user_details (
  user_details_id int(11) NOT NULL AUTO_INCREMENT,
  fname varchar(255) DEFAULT 'NULL',
  lname varchar(255) DEFAULT 'NULL',
  address varchar(255) DEFAULT 'NULL',
  age int(11) DEFAULT NULL,
  bday varchar(255) DEFAULT 'NULL',
  PRIMARY KEY (user_details_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE user_cred (
  username varchar(255) NOT NULL DEFAULT '''''''NULL''''''',
  user_cred_id int(11) NOT NULL AUTO_INCREMENT,
  password varchar(255) NOT NULL DEFAULT '''NULL''',
  user_details_id int(11) NOT NULL,
  flag varchar(255) DEFAULT 'NULL',
  PRIMARY KEY (user_cred_id),
  CONSTRAINT FK_user_cred_user_details_user_details_id FOREIGN KEY (user_details_id)
  REFERENCES user_details (user_details_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;